export function buildCategoryManagementSectionProps(options) {
  return {
    activeCategory: options.activeCategory,
    activeCategoryId: options.activeCategoryId,
    categories: options.categories,
    categoriesPerPage: options.categoriesPerPage,
    categoryCatalogTotalItems: options.categoryCatalogTotalItems,
    categoryCatalogTotalPages: options.categoryCatalogTotalPages,
    categoryPage: options.categoryPage,
    categorySearch: options.categorySearch,
    categorySort: options.categorySort,
    createCategoryForm: options.createCategoryForm,
    editCategoryForm: options.editCategoryForm,
    filteredCategoryIds: options.filteredCategoryIds,
    handleCategorySelect: options.handleCategorySelect,
    handleClearAllSelectedCategories: options.handleClearAllSelectedCategories,
    handleCreateCategory: options.handleCreateCategory,
    handleOpenCategoryProducts: options.handleOpenCategoryProducts,
    handleSelectAllFilteredCategories: options.handleSelectAllFilteredCategories,
    handleToggleSelectedCategoryId: options.handleToggleSelectedCategoryId,
    handleUpdateCategory: options.handleUpdateCategory,
    hasSelectedCategories: options.hasSelectedCategories,
    isCreatingCategory: options.isCreatingCategory,
    isDeletingCategory: options.isDeletingCategory,
    isUpdatingCategory: options.isUpdatingCategory,
    loading: options.loading,
    openCatalogMenu: options.openCatalogMenu,
    openCategoryDeleteModal: options.openCategoryDeleteModal,
    presentation: options.presentation,
    selectedCategoryIds: options.selectedCategoryIds,
    selectedCategoriesPerPage: options.selectedCategoriesPerPage,
    selectedCategorySort: options.selectedCategorySort,
    setCategoryPage: options.setCategoryPage,
    setCategorySearch: options.setCategorySearch,
    setCategorySort: options.setCategorySort,
    setCategoriesPerPage: options.setCategoriesPerPage,
    setOpenCatalogMenu: options.setOpenCatalogMenu,
  }
}

export function buildCategoryDeleteModalProps(options) {
  return {
    categoryDeleteModalState: options.categoryDeleteModalState,
    categoryDeletePreview: options.categoryDeletePreview,
    closeCategoryDeleteModal: options.closeCategoryDeleteModal,
    deleteModalCategories: options.deleteModalCategories,
    handleDeleteSelectedCategories: options.handleDeleteSelectedCategories,
    isDeletePreviewLoading: options.isDeletePreviewLoading,
    isDeletingCategory: options.isDeletingCategory,
    truncateLabel: options.truncateLabel,
  }
}

export function buildCategorySelectionSidebarProps(options) {
  return {
    activeCategory: options.activeCategory,
    createCategoryForm: options.createCategoryForm,
    editCategoryForm: options.editCategoryForm,
    handleCategorySelect: options.handleCategorySelect,
    handleClearAllSelectedCategories: options.handleClearAllSelectedCategories,
    handleRemoveSelectedCategoryId: options.handleRemoveSelectedCategoryId,
    mergeCategoryForm: options.mergeCategoryForm,
    handleCreateCategory: options.handleCreateCategory,
    handleMergeCategories: options.handleMergeCategories,
    handleUpdateCategory: options.handleUpdateCategory,
    isCreatingCategory: options.isCreatingCategory,
    isDeletingCategory: options.isDeletingCategory,
    isMergingCategories: options.isMergingCategories,
    isUpdatingCategory: options.isUpdatingCategory,
    presentation: options.presentation,
    selectedCategories: options.selectedCategories,
    selectedCategoryIds: options.selectedCategoryIds,
    selectedCategoryCount: options.selectedCategoryCount,
    setCreateCategoryForm: options.setCreateCategoryForm,
    setEditCategoryForm: options.setEditCategoryForm,
    setMergeCategoryForm: options.setMergeCategoryForm,
    totalCategoryCount: options.totalCategoryCount,
    truncateLabel: options.truncateLabel,
  }
}
