export function buildClientDirectoryPanelProps(options) {
  return {
    actionInfo: options.actionInfo,
    activeClient: options.activeClient,
    activeClientId: options.activeClientId,
    catalog: options.catalog,
    clientConnectionFilter: options.clientConnectionFilter,
    clientPage: options.clientPage,
    clientSearch: options.clientSearch,
    clientSort: options.clientSort,
    clientStatusFilter: options.clientStatusFilter,
    clientVerificationFilter: options.clientVerificationFilter,
    clientsPerPage: options.clientsPerPage,
    isCatalogLoading: options.isCatalogLoading,
    isBulkAccountStatusSubmitting: options.isBulkAccountStatusSubmitting,
    onlineClientIdSet: options.onlineClientIdSet,
    onlineClientTotal: options.onlineClientTotal,
    selectedClientConnectionFilter: options.selectedClientConnectionFilter,
    selectedClientIds: options.selectedClientIds,
    selectedClientSort: options.selectedClientSort,
    selectedClientStatusFilter: options.selectedClientStatusFilter,
    selectedClientSummary: options.selectedClientSummary,
    selectedClientVerificationFilter: options.selectedClientVerificationFilter,
    selectedClientsPerPage: options.selectedClientsPerPage,
    visibleClients: options.visibleClients,
    onChangeConnectionFilter: options.onChangeConnectionFilter,
    onChangePage: options.onChangePage,
    onChangePageSize: options.onChangePageSize,
    onChangeSearch: options.onChangeSearch,
    onChangeSort: options.onChangeSort,
    onChangeStatusFilter: options.onChangeStatusFilter,
    onChangeVerificationFilter: options.onChangeVerificationFilter,
    onDeactivateSelectedClients: options.onDeactivateSelectedClients,
    onActivateSelectedClients: options.onActivateSelectedClients,
    onToggleSelectedClients: options.onToggleSelectedClients,
    onClearVisibleSelection: options.onClearVisibleSelection,
    onSelectClient: options.onSelectClient,
    onSelectVisibleClients: options.onSelectVisibleClients,
    onToggleClientSelection: options.onToggleClientSelection,
    openCatalogMenu: options.openCatalogMenu,
    setActionInfo: options.setActionInfo,
    setOpenCatalogMenu: options.setOpenCatalogMenu,
  }
}

export function buildClientSelectionSidebarProps(options) {
  return {
    activeClient: options.activeClient,
    clientProfile: options.clientProfile,
    deliveryAddresses: options.deliveryAddresses,
    deliveryError: options.deliveryError,
    isAccountStatusSubmitting: options.isAccountStatusSubmitting,
    isDeliveryLoading: options.isDeliveryLoading,
    isDeliveryUpdating: options.isDeliveryUpdating,
    isPaymentLoading: options.isPaymentLoading,
    isPaymentUpdating: options.isPaymentUpdating,
    isProfileLoading: options.isProfileLoading,
    isProfileUpdating: options.isProfileUpdating,
    onToggleClientAccountStatus: options.onToggleClientAccountStatus,
    onlineClientIdSet: options.onlineClientIdSet,
    paymentError: options.paymentError,
    paymentMethods: options.paymentMethods,
    profileError: options.profileError,
  }
}
