export function buildProductCreatePanelProps(options) {
  return {
    activeCreateDraft: options.activeCreateDraft,
    activeSectionId: options.activeSectionId,
    createCategoryDraft: options.createCategoryDraft,
    createDirtyFields: options.createDirtyFields,
    createForm: options.createForm,
    createImageUrls: options.createImageUrls,
    createImageUrlDraft: options.createImageUrlDraft,
    createPromotionActive: options.createPromotionActive,
    createPreviewPrice: options.createPreviewPrice,
    filteredCreateCategories: options.filteredCreateCategories,
    handleAddCreateImageUrl: options.handleAddCreateImageUrl,
    handleBulkProductCreate: options.handleBulkProductCreate,
    handleCreateFieldChange: options.handleCreateFieldChange,
    handleCreateImagesUpload: options.handleCreateImagesUpload,
    handleCreateProductCategory: options.handleCreateProductCategory,
    handleProductCreate: options.handleProductCreate,
    handleRemoveCreateImage: options.handleRemoveCreateImage,
    handleResetCreateChanges: options.handleResetCreateChanges,
    handleSelectCreatePrimaryImage: options.handleSelectCreatePrimaryImage,
    handleSetCreatePreviewImage: options.handleSetCreatePreviewImage,
    hasMultipleDrafts: options.hasMultipleDrafts,
    isCreateDirty: options.isCreateDirty,
    isCreatingCategory: options.isCreatingCategory,
    isCreatingProduct: options.isCreatingProduct,
    isDeletingCategory: options.isDeletingCategory,
    isUploadingCreateImages: options.isUploadingCreateImages,
    openCatalogMenu: options.openCatalogMenu,
    selectedCreateCategoryLabel: options.selectedCreateCategoryLabel,
    selectedCreatePreviewImage: options.selectedCreatePreviewImage,
    setCreateCategoryDraft: options.setCreateCategoryDraft,
    setCreateImageUrlDraft: options.setCreateImageUrlDraft,
    setOpenCatalogMenu: options.setOpenCatalogMenu,
  }
}

export function buildProductEditPanelProps(options) {
  return {
    deferredEditDescription: options.deferredEditDescription,
    descriptionInputValue: options.descriptionInputValue,
    editCategoryDraft: options.editCategoryDraft,
    editDirtyFields: options.editDirtyFields,
    editForm: options.editForm,
    editImageUrls: options.editImageUrls,
    editPreviewImage: options.editPreviewImage,
    editPreviewSidebarSlots: options.editPreviewSidebarSlots,
    editingProduct: options.editingProduct,
    filteredEditCategories: options.filteredEditCategories,
    handleAddImageUrl: options.handleAddImageUrl,
    handleCreateEditCategory: options.handleCreateEditCategory,
    handleEditFieldChange: options.handleEditFieldChange,
    handleImagesUpload: options.handleImagesUpload,
    handleProductSave: options.handleProductSave,
    handleRemoveImage: options.handleRemoveImage,
    handleResetEditChanges: options.handleResetEditChanges,
    handleSelectPrimaryImage: options.handleSelectPrimaryImage,
    handleSetDescriptionInputValue: options.handleSetDescriptionInputValue,
    imageUrlDraft: options.imageUrlDraft,
    isCreatingCategory: options.isCreatingCategory,
    isDeletingCategory: options.isDeletingCategory,
    isEditDirty: options.isEditDirty,
    isSaving: options.isSaving,
    isUploadingImages: options.isUploadingImages,
    loading: options.loading,
    openCatalogMenu: options.openCatalogMenu,
    selectedEditCategoryLabel: options.selectedEditCategoryLabel,
    setEditCategoryDraft: options.setEditCategoryDraft,
    setImageUrlDraft: options.setImageUrlDraft,
    setOpenCatalogMenu: options.setOpenCatalogMenu,
    handleSetEditPreviewImage: options.handleSetEditPreviewImage,
  }
}

export function buildProductSelectionSidebarProps(options) {
  return {
    activeSidebarItemKey: options.activeSidebarItemKey,
    dirtyCreateDrafts: options.dirtyCreateDrafts,
    dirtySelectedProductsForSidebar: options.dirtySelectedProductsForSidebar,
    getProductImage: options.getProductImage,
    handleClearPendingSelection: options.handleClearPendingSelection,
    handleRemoveCreateDraft: options.handleRemoveCreateDraft,
    handleRemovePendingSelectedProduct: options.handleRemovePendingSelectedProduct,
    handleSaveDirtySelection: options.handleSaveDirtySelection,
    handleSelectCreateDraft: options.handleSelectCreateDraft,
    isSavingDirtySelection: options.isSavingDirtySelection,
    navigate: options.navigate,
    openUnsavedSelectionModal: options.openUnsavedSelectionModal,
    selectionSummary: options.selectionSummary,
    truncateLabel: options.truncateLabel,
    untouchedCreateDrafts: options.untouchedCreateDrafts,
    untouchedSelectedProductsForSidebar: options.untouchedSelectedProductsForSidebar,
  }
}

export function buildProductDeletePanelProps(options) {
  return {
    guardedNavigate: options.guardedNavigate,
    isDeletingProducts: options.isDeletingProducts,
    openDeleteProductsModal: options.openDeleteProductsModal,
    productsById: options.productsById,
    selectedProductIds: options.selectedProductIds,
    truncateLabel: options.truncateLabel,
  }
}
