import useProductWorkspaceState from './useProductWorkspaceState'
import useAdminProductPageDerived from './useAdminProductPageDerived'
import useAdminProductWorkspaceController from './useAdminProductWorkspaceController'

export default function useAdminProductWorkspaceModule({
  activeSectionId,
  createCategoryDraft,
  createForm,
  descriptionInputValue,
  editCategoryDraft,
  editDraftsByProductId,
  editForm,
  editingProduct,
  initialCreateForm,
  initialEditForm,
  isCreateSection,
  locationHash,
  navigate,
  pageType,
  productId,
  productImportModalOpen,
  resources,
  selectedPreviewImage,
  setCreateCategoryDraft,
  setCreateForm,
  setCreateImageUrlDraft,
  setDescriptionInputValue,
  setEditCategoryDraft,
  setEditDraftsByProductId,
  setEditForm,
  setEditingProduct,
  setError,
  setImageUrlDraft,
  setInitialCreateForm,
  setInitialEditForm,
  setIsCreatingCategory,
  setLoading,
  setSelectedCreatePreviewImage,
  setSelectedPreviewImage,
}) {
  const workspaceState = useProductWorkspaceState({
    categories: resources.categories,
    editDraftsByProductId,
    isCreateSection,
    navigate,
    pageType,
    productId,
    products: resources.products,
    setCreateCategoryDraft,
    setCreateForm,
    setCreateImageUrlDraft,
    setEditDraftsByProductId,
    setError,
    setInitialCreateForm,
    setSelectedCreatePreviewImage,
  })

  const derivedPageState = useAdminProductPageDerived({
    activeSectionId,
    editDraftsByProductId,
    managedEditProductId: workspaceState.managedEditProductId,
    navigate,
    pageType,
    productImportModalOpen,
    products: resources.products,
    productsById: resources.productsById,
    selectedProductIds: workspaceState.selectedProductIds,
    workspaceState,
  })

  const workspaceController = useAdminProductWorkspaceController({
    activeSectionId,
    activeCreateDraftId: workspaceState.activeCreateDraftId,
    categories: resources.categories,
    createCategoryDraft,
    createDrafts: workspaceState.createDrafts,
    createForm,
    deleteModalState: workspaceState.deleteModalState,
    descriptionInputValue,
    editCategoryDraft,
    editDraftsByProductId,
    editForm,
    editingProduct,
    initialCreateForm,
    initialEditForm,
    isCreateSection,
    locationHash,
    navigate,
    pageType,
    pendingCreateDrafts: workspaceState.pendingCreateDrafts,
    productId,
    products: resources.products,
    productsById: resources.productsById,
    savedCreateDraftIds: workspaceState.savedCreateDraftIds,
    selectedPreviewImage,
    selectedProductIds: derivedPageState.productWorkspaceModel.selectedIds,
    setActiveCreateDraftId: workspaceState.setActiveCreateDraftId,
    setCategories: resources.setCategories,
    setCreateCategoryDraft,
    setCreateDrafts: workspaceState.setCreateDrafts,
    setCreateForm,
    setCreateImageUrlDraft,
    setDescriptionInputValue,
    setEditCategoryDraft,
    setEditDraftsByProductId,
    setEditForm,
    setEditingProduct,
    setError,
    setImageUrlDraft,
    setInitialEditForm,
    setIsCreatingCategory,
    setLoading,
    setModificationProductIds: workspaceState.setModificationProductIds,
    setSavedCreateDraftIds: workspaceState.setSavedCreateDraftIds,
    setIsClosingCreateWorkspace: workspaceState.setIsClosingCreateWorkspace,
    setSelectedCreatePreviewImage,
    setSelectedPreviewImage,
    setSelectedProductIds: workspaceState.setSelectedProductIds,
    setInitialCreateForm,
    unsavedSelectionModalState: workspaceState.unsavedSelectionModalState,
    closeUnsavedSelectionModal: workspaceState.closeUnsavedSelectionModal,
    mapProductIdsToProducts: derivedPageState.mapProductIdsToProducts,
  })

  return {
    derivedPageState,
    workspaceController,
    workspaceState,
  }
}
