--
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE admin_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(190) NOT NULL,
    nom character varying(120) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(32) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: admin_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE admin_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alert_cooldown; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE alert_cooldown (
    id bigint NOT NULL,
    alert_count integer NOT NULL,
    alert_key character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_error_hash character varying(64),
    last_sent_at timestamp(6) with time zone NOT NULL
);


--
-- Name: alert_cooldown_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE alert_cooldown ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alert_cooldown_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_ideas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE content_ideas (
    id bigint NOT NULL,
    background_keyword character varying(255),
    caption character varying(255),
    category character varying(255),
    created_at timestamp(6) with time zone,
    final_video_status character varying(255),
    pipeline_status character varying(255),
    platform character varying(255),
    publish_status character varying(255),
    published_at timestamp(6) with time zone,
    render_payload text,
    render_status character varying(255),
    script_status character varying(255),
    scripts character varying(255),
    shotstack_render_id character varying(255),
    shotstack_status character varying(255),
    shotstack_url character varying(255),
    status character varying(255),
    template_id character varying(255),
    tiktok_account_open_id character varying(255),
    tiktok_check_status character varying(255),
    tiktok_publish_id character varying(255),
    tiktok_upload_status character varying(255),
    tiktok_upload_url character varying(255),
    topic character varying(255),
    updated_at timestamp(6) with time zone,
    uploaded_at timestamp(6) with time zone
);


--
-- Name: content_ideas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE content_ideas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME content_ideas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_connections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE service_connections (
    id bigint NOT NULL,
    account_identifier character varying(255),
    base_url character varying(500),
    connected_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(120),
    last_validated_at timestamp(6) with time zone,
    metadata_json text,
    provider_key character varying(40) NOT NULL,
    secret_value text,
    status character varying(24) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    last_validation_message character varying(500),
    last_validation_status character varying(24),
    is_active boolean DEFAULT false,
    CONSTRAINT service_connections_last_validation_status_check CHECK (((last_validation_status)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'VALID'::character varying, 'INVALID'::character varying])::text[]))),
    CONSTRAINT service_connections_provider_key_check CHECK (((provider_key)::text = ANY ((ARRAY['SHOTSTACK'::character varying, 'GROQ'::character varying, 'N8N'::character varying, 'PEXELS'::character varying, 'SUPABASE'::character varying])::text[]))),
    CONSTRAINT service_connections_status_check CHECK (((status)::text = ANY ((ARRAY['CONNECTED'::character varying, 'DISCONNECTED'::character varying])::text[])))
);


--
-- Name: service_connections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE service_connections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME service_connections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tiktok_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE tiktok_accounts (
    id bigint NOT NULL,
    access_token character varying(255),
    created_at timestamp(6) with time zone,
    open_id character varying(255),
    refresh_token character varying(255),
    scope character varying(255),
    token_type character varying(255),
    updated_at timestamp(6) with time zone,
    access_token_expires_at timestamp(6) with time zone,
    last_token_refresh_at timestamp(6) with time zone,
    last_token_refresh_error character varying(500),
    refresh_token_expires_at timestamp(6) with time zone,
    token_status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL
);


--
-- Name: tiktok_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE tiktok_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tiktok_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video_pipeline_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE video_pipeline_events (
    id bigint NOT NULL,
    content_idea_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    event_type character varying(80) NOT NULL,
    message character varying(500) NOT NULL,
    payload_json oid,
    severity character varying(24) NOT NULL,
    workflow_run_id bigint
);


--
-- Name: video_pipeline_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE video_pipeline_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME video_pipeline_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video_pipeline_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE video_pipeline_states (
    content_idea_id bigint NOT NULL,
    last_error_message character varying(500),
    last_workflow_run_id bigint,
    last_workflow_type character varying(40),
    pipeline_stage character varying(40) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint,
    CONSTRAINT video_pipeline_states_last_workflow_type_check CHECK (((last_workflow_type IS NULL) OR ((last_workflow_type)::text = ANY ((ARRAY['MAIN_PIPELINE'::character varying, 'SCRIPT_GENERATION'::character varying, 'CHECK_SHOTSTACK'::character varying, 'RENDER_TEMPLATE_VIDEO'::character varying, 'INIT_PUBLISH_TIKTOK'::character varying, 'TIKTOK_UPLOAD'::character varying, 'FINALIZE_PUBLISH'::character varying])::text[])))),
    CONSTRAINT video_pipeline_states_pipeline_stage_check CHECK (((pipeline_stage)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'CREATION_REQUESTED'::character varying, 'IDEA_CREATED'::character varying, 'SCRIPT_REQUESTED'::character varying, 'SCRIPT_READY'::character varying, 'RENDERING_REQUESTED'::character varying, 'RENDER_READY'::character varying, 'UPLOAD_PREPARING'::character varying, 'PUBLISH_INITIALIZED'::character varying, 'UPLOAD_COMPLETED'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: video_publish_batch_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE video_publish_batch_items (
    id bigint NOT NULL,
    attempt_number integer NOT NULL,
    batch_id character varying(36) NOT NULL,
    completed_at timestamp(6) with time zone,
    content_idea_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    error_message character varying(1000),
    status character varying(24) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    workflow_run_id bigint,
    CONSTRAINT video_publish_batch_items_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: video_publish_batch_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE video_publish_batch_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME video_publish_batch_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video_publish_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE video_publish_batches (
    id character varying(36) NOT NULL,
    completed_at timestamp(6) with time zone,
    completed_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    failed_count integer NOT NULL,
    requested_by_email character varying(190),
    status character varying(24) NOT NULL,
    tiktok_account_open_id character varying(190),
    total_count integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT video_publish_batches_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'COMPLETED'::character varying, 'PARTIAL_FAILURE'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: video_workflow_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE video_workflow_runs (
    id bigint NOT NULL,
    attempt_number integer NOT NULL,
    completed_at timestamp(6) with time zone,
    content_idea_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    error_message character varying(500),
    force_requested boolean NOT NULL,
    idempotency_key character varying(190) NOT NULL,
    request_payload oid,
    requested_by_email character varying(190),
    response_payload oid,
    status character varying(32) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    workflow_type character varying(40) NOT NULL,
    CONSTRAINT video_workflow_runs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT video_workflow_runs_workflow_type_check CHECK (((workflow_type)::text = ANY ((ARRAY['MAIN_PIPELINE'::character varying, 'SCRIPT_GENERATION'::character varying, 'CHECK_SHOTSTACK'::character varying, 'RENDER_TEMPLATE_VIDEO'::character varying, 'INIT_PUBLISH_TIKTOK'::character varying, 'TIKTOK_UPLOAD'::character varying, 'FINALIZE_PUBLISH'::character varying])::text[])))
);


--
-- Name: video_workflow_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE video_workflow_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME video_workflow_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_accounts admin_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY admin_accounts
    ADD CONSTRAINT admin_accounts_pkey PRIMARY KEY (id);


--
-- Name: alert_cooldown alert_cooldown_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY alert_cooldown
    ADD CONSTRAINT alert_cooldown_pkey PRIMARY KEY (id);


--
-- Name: content_ideas content_ideas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY content_ideas
    ADD CONSTRAINT content_ideas_pkey PRIMARY KEY (id);


--
-- Name: service_connections service_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY service_connections
    ADD CONSTRAINT service_connections_pkey PRIMARY KEY (id);


--
-- Name: tiktok_accounts tiktok_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tiktok_accounts
    ADD CONSTRAINT tiktok_accounts_pkey PRIMARY KEY (id);


--
-- Name: admin_accounts ukqcarmmr0abdqt7677ea2hbpbh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY admin_accounts
    ADD CONSTRAINT ukqcarmmr0abdqt7677ea2hbpbh UNIQUE (email);


--
-- Name: alert_cooldown uks9a4n85igt9he5rla4uq6ofo9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY alert_cooldown
    ADD CONSTRAINT uks9a4n85igt9he5rla4uq6ofo9 UNIQUE (alert_key);


--
-- Name: video_pipeline_events video_pipeline_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY video_pipeline_events
    ADD CONSTRAINT video_pipeline_events_pkey PRIMARY KEY (id);


--
-- Name: video_pipeline_states video_pipeline_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY video_pipeline_states
    ADD CONSTRAINT video_pipeline_states_pkey PRIMARY KEY (content_idea_id);


--
-- Name: video_publish_batch_items video_publish_batch_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY video_publish_batch_items
    ADD CONSTRAINT video_publish_batch_items_pkey PRIMARY KEY (id);


--
-- Name: video_publish_batches video_publish_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY video_publish_batches
    ADD CONSTRAINT video_publish_batches_pkey PRIMARY KEY (id);


--
-- Name: video_workflow_runs video_workflow_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY video_workflow_runs
    ADD CONSTRAINT video_workflow_runs_pkey PRIMARY KEY (id);


--
-- Name: idx_alert_cooldown_last_sent_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alert_cooldown_last_sent_at ON alert_cooldown USING btree (last_sent_at);


--
-- Name: idx_batch_items_batch_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batch_items_batch_id ON video_publish_batch_items USING btree (batch_id);


--
-- Name: idx_batch_items_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batch_items_status ON video_publish_batch_items USING btree (status);


--
--


