-- Phase 6 - Persist Remotion render metadata on content_ideas.
-- quality_profile : draft / standard / high / premium (Remotion FFmpeg post-process)
-- render_engine   : shotstack / remotion (engine actually used for the latest render)
-- thumbnail_url   : poster JPG generated by the Remotion service at 0.5s

ALTER TABLE content_ideas
    ADD COLUMN IF NOT EXISTS quality_profile VARCHAR(32),
    ADD COLUMN IF NOT EXISTS render_engine   VARCHAR(32),
    ADD COLUMN IF NOT EXISTS thumbnail_url   VARCHAR(2048);
