import { useState } from 'react'
import useProductFormImageMutations from './useProductFormImageMutations'
import useProductPersistenceMutations from './useProductPersistenceMutations.js'
import useProductBulkMutations from './useProductBulkMutations.js'
import useProductCatalogMutations from './useProductCatalogMutations.js'

export default function useProductMutations({
  activeCreateDraftId,
  appendProductSessionActivity,
  categories,
  editDraftsByProductId,
  createDrafts,
  createForm,
  createImageUrlDraft,
  deleteModalState,
  descriptionInputValue,
  editForm,
  editImageUrls,
  editingProduct,
  imageUrlDraft,
  initialEditForm,
  invalidateProductCatalog,
  isCreateSection,
  navigate,
  products,
  productsById,
  refreshCategories,
  resolvedEditProductId,
  savedCreateDraftIds,
  selectedCategory,
  selectedCreateCategory,
  selectedCreatePreviewImage,
  selectedPreviewImage,
  selectedProductIds,
  setActiveCreateDraftId,
  setCreateCategoryDraft,
  setCreateDrafts,
  setCreateForm,
  setCreateImageUrlDraft,
  setDeleteModalState,
  setDescriptionInputValue,
  setEditCategoryDraft,
  setEditDraftsByProductId,
  setEditForm,
  setEditingProduct,
  setError,
  setImageUrlDraft,
  setInfo,
  setInitialCreateForm,
  setInitialEditForm,
  setManagedEditProductId,
  setModificationProductIds,
  setSavedCreateDraftIds,
  setSelectedCreatePreviewImage,
  setSelectedPreviewImage,
  setSelectedProductIds,
  removeProductsFromCache,
  upsertProductsInCache,
  guardedNavigate,
}) {
  const [isSaving, setIsSaving] = useState(false)
  const [isSavingDirtySelection, setIsSavingDirtySelection] = useState(false)
  const [isCreatingProduct, setIsCreatingProduct] = useState(false)
  const [isDeletingProducts, setIsDeletingProducts] = useState(false)
  const [deleteProgressPercent, setDeleteProgressPercent] = useState(0)
  const [isUpdatingProductPublishStatus, setIsUpdatingProductPublishStatus] = useState(false)

  const imageMutations = useProductFormImageMutations({
    activeCreateDraftId,
    categories,
    createForm,
    createImageUrlDraft,
    editImageUrls,
    editingProduct,
    imageUrlDraft,
    initialEditForm,
    isCreateSection,
    selectedCreatePreviewImage,
    selectedPreviewImage,
    setCreateCategoryDraft,
    setCreateDrafts,
    setCreateForm,
    setCreateImageUrlDraft,
    setDescriptionInputValue,
    setEditCategoryDraft,
    setEditForm,
    setError,
    setImageUrlDraft,
    setInfo,
    setInitialCreateForm,
    setSavedCreateDraftIds,
    setSelectedCreatePreviewImage,
    setSelectedPreviewImage,
  })

  const persistenceMutations = useProductPersistenceMutations({
    activeCreateDraftId,
    appendProductSessionActivity,
    createDrafts,
    createForm,
    descriptionInputValue,
    editDraftsByProductId,
    editForm,
    editingProduct,
    invalidateProductCatalog,
    navigate,
    products,
    resolvedEditProductId,
    savedCreateDraftIds,
    selectedCategory,
    selectedCreateCategory,
    selectedProductIds,
    setActiveCreateDraftId,
    setCreateDrafts,
    setCreateForm,
    setCreateImageUrlDraft,
    setEditCategoryDraft,
    setEditDraftsByProductId,
    setEditForm,
    setEditingProduct,
    setError,
    setInfo,
    setInitialCreateForm,
    setInitialEditForm,
    setIsCreatingProduct,
    setIsSaving,
    setModificationProductIds,
    setSavedCreateDraftIds,
    setSelectedCreatePreviewImage,
    setSelectedProductIds,
    upsertProductsInCache,
  })

  const bulkMutations = useProductBulkMutations({
    appendProductSessionActivity,
    categories,
    createDrafts,
    editDraftsByProductId,
    invalidateProductCatalog,
    navigate,
    resetCreateWorkspace: persistenceMutations.resetCreateWorkspace,
    resolvedEditProductId,
    savedCreateDraftIds,
    setActiveCreateDraftId,
    setCreateImageUrlDraft,
    setEditCategoryDraft,
    setEditDraftsByProductId,
    setEditForm,
    setEditingProduct,
    setError,
    setInfo,
    setInitialEditForm,
    setIsCreatingProduct,
    setIsSavingDirtySelection,
    setModificationProductIds,
    setSelectedProductIds,
    upsertProductsInCache,
  })

  const catalogMutations = useProductCatalogMutations({
    appendProductSessionActivity,
    createDrafts,
    deleteModalState,
    guardedNavigate,
    invalidateProductCatalog,
    productsById,
    refreshCategories,
    removeProductsFromCache,
    selectedProductIds,
    setCreateDrafts,
    setDeleteModalState,
    setError,
    setInfo,
    setIsDeletingProducts,
    setDeleteProgressPercent,
    setIsUpdatingProductPublishStatus,
    setManagedEditProductId,
    setModificationProductIds,
    setSavedCreateDraftIds,
    setSelectedProductIds,
    upsertProductsInCache,
  })

  return {
    ...imageMutations,
    handleBulkProductCreate: bulkMutations.handleBulkProductCreate,
    handleBulkProductDelete: catalogMutations.handleBulkProductDelete,
    handleBulkProductPublishStatus: catalogMutations.handleBulkProductPublishStatus,
    handleProductCreate: persistenceMutations.handleProductCreate,
    handleProductSave: persistenceMutations.handleProductSave,
    handleSaveDirtySelection: bulkMutations.handleSaveDirtySelection,
    isCreatingProduct,
    deleteProgressPercent,
    isDeletingProducts,
    isSaving,
    isSavingDirtySelection,
    isUpdatingProductPublishStatus,
  }
}
