import process from 'node:process'
import { test, expect } from '@playwright/test'

const enabled = process.env.PLAYWRIGHT_ENABLE_VIDEO_OPS_E2E === 'true'

test.skip(!enabled, 'Set PLAYWRIGHT_ENABLE_VIDEO_OPS_E2E=true to run the TikTok journey smoke test.')

test('runs the minimal TikTok journey from creation to prepare upload', async ({ page }) => {
  let nextIdeaId = 900
  let nextRunId = 3000
  let ideas = []
  let lastWorkflowRun = null

  const connectedAccount = [{
    id: 5,
    nickname: 'sandbox-account',
    openId: 'open-demo-1234567890',
    scope: 'user.info.basic,video.publish',
    environment: 'sandbox',
    status: 'connected',
  }]

  const buildStatus = (idea) => ({
    contentIdeaId: idea.id,
    topic: idea.topic,
    pipelineStage: String(idea.pipelineStatus || '').toUpperCase(),
    pipelineStageLabel: idea.pipelineStatus,
    shotstackStatus: idea.shotstackStatus || '',
    finalVideoStatus: idea.finalVideoStatus || '',
    tiktokStatus: idea.tiktokStatus || '',
    tiktokUploadStatus: idea.tiktokUploadStatus || '',
    tiktokAccountOpenId: idea.tiktokAccountOpenId || connectedAccount[0].openId,
    shotstackUrl: idea.shotstackUrl || '',
    uploadUrl: idea.uploadUrl || '',
    lastErrorMessage: null,
    lastWorkflowRun,
    lastEventMessage: lastWorkflowRun?.status === 'SUCCEEDED' ? 'Workflow termine avec succes.' : 'Workflow en cours.',
    lastEventSeverity: lastWorkflowRun?.status === 'SUCCEEDED' ? 'INFO' : 'WARN',
    lastUpdatedAt: new Date().toISOString(),
  })

  await page.addInitScript(() => {
    window.localStorage.setItem('tiktok_app_admin_remember_me', 'true')
    window.localStorage.setItem('tiktok_app_admin_session', JSON.stringify({
      token: 'playwright-admin-token',
      expiresAt: Date.now() + 60 * 60 * 1000,
      role: 'ADMIN',
      user: { email: 'admin@tiktokapp.local', nom: 'Video Ops Admin' },
    }))
  })

  await page.route('**/api/video-ops/**', async (route) => {
    const { pathname } = new URL(route.request().url())
    const method = route.request().method()

    if (method === 'GET' && pathname.endsWith('/tiktok-accounts')) {
      await route.fulfill({ json: connectedAccount })
      return
    }

    if (method === 'GET' && pathname.endsWith('/content-ideas')) {
      await route.fulfill({ json: ideas })
      return
    }

    if (method === 'GET' && pathname.endsWith('/manual-actions')) {
      const manualActions = ideas
        .filter((idea) => idea.shotstackUrl || idea.uploadUrl)
        .map((idea) => ({
          id: idea.id,
          topic: idea.topic,
          shotstackUrl: idea.shotstackUrl || '',
          uploadUrl: idea.uploadUrl || '',
          workflowStatus: idea.pipelineStatus || '',
          tiktokStatus: idea.tiktokStatus || '',
          finalVideoStatus: idea.finalVideoStatus || '',
          shotstackStatus: idea.shotstackStatus || '',
          pipelineStatus: idea.pipelineStatus || '',
          lastError: null,
        }))
      await route.fulfill({ json: manualActions })
      return
    }

    if (method === 'GET' && pathname.includes('/content-ideas/') && pathname.endsWith('/status')) {
      const ideaId = Number(pathname.split('/').slice(-2)[0])
      const idea = ideas.find((entry) => entry.id === ideaId)
      await route.fulfill({ json: buildStatus(idea) })
      return
    }

    if (method === 'GET' && pathname.includes('/workflow-runs/')) {
      await route.fulfill({
        json: lastWorkflowRun || {
          id: nextRunId,
          contentIdeaId: null,
          workflowType: 'MAIN_PIPELINE',
          status: 'SUCCEEDED',
          attemptNumber: 1,
          errorMessage: null,
          responsePayload: '{}',
          createdAt: new Date().toISOString(),
          completedAt: new Date().toISOString(),
        },
      })
      return
    }

    if (method === 'POST' && pathname.endsWith('/workflows/main-pipeline')) {
      const body = JSON.parse(route.request().postData() || '{}')
      const idea = {
        id: ++nextIdeaId,
        category: body.category,
        topic: 'Food idea generated by Playwright',
        script: '',
        caption: '',
        keyword: '',
        shotstackStatus: '',
        tiktokStatus: 'draft',
        finalVideoStatus: '',
        shotstackUrl: '',
        uploadUrl: '',
        tiktokAccountOpenId: body.tiktokAccountOpenId,
        pipelineStatus: 'idea_created',
        lastError: null,
      }
      ideas = [idea, ...ideas]
      lastWorkflowRun = {
        id: ++nextRunId,
        contentIdeaId: idea.id,
        workflowType: 'MAIN_PIPELINE',
        status: 'SUCCEEDED',
        attemptNumber: 1,
        errorMessage: null,
        responsePayload: '{}',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
      }
      await route.fulfill({ json: { runId: lastWorkflowRun.id, workflowType: lastWorkflowRun.workflowType, status: 'ACCEPTED' } })
      return
    }

    if (method === 'POST' && pathname.endsWith('/workflows/check-shotstack')) {
      const body = JSON.parse(route.request().postData() || '{}')
      ideas = ideas.map((idea) => idea.id === Number(body.contentIdeaId)
        ? {
            ...idea,
            script: 'Script genere automatiquement',
            caption: 'Caption generee automatiquement',
            keyword: 'food',
            pipelineStatus: 'script_ready',
          }
        : idea)
      lastWorkflowRun = {
        id: ++nextRunId,
        contentIdeaId: Number(body.contentIdeaId),
        workflowType: 'CHECK_SHOTSTACK',
        status: 'SUCCEEDED',
        attemptNumber: 1,
        errorMessage: null,
        responsePayload: '{}',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
      }
      await route.fulfill({ json: { runId: lastWorkflowRun.id, workflowType: lastWorkflowRun.workflowType, status: 'ACCEPTED' } })
      return
    }

    if (method === 'POST' && pathname.endsWith('/workflows/render-template')) {
      const body = JSON.parse(route.request().postData() || '{}')
      ideas = ideas.map((idea) => idea.id === Number(body.contentIdeaId)
        ? {
            ...idea,
            shotstackStatus: 'done',
            finalVideoStatus: 'ready',
            shotstackUrl: 'https://shotstack-api-v1-output.s3-ap-southeast-2.amazonaws.com/demo.mp4',
            pipelineStatus: 'render_ready',
          }
        : idea)
      lastWorkflowRun = {
        id: ++nextRunId,
        contentIdeaId: Number(body.contentIdeaId),
        workflowType: 'RENDER_TEMPLATE_VIDEO',
        status: 'SUCCEEDED',
        attemptNumber: 1,
        errorMessage: null,
        responsePayload: '{}',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
      }
      await route.fulfill({ json: { runId: lastWorkflowRun.id, workflowType: lastWorkflowRun.workflowType, status: 'ACCEPTED' } })
      return
    }

    if (method === 'POST' && pathname.endsWith('/workflows/init-publish')) {
      const body = JSON.parse(route.request().postData() || '{}')
      ideas = ideas.map((idea) => idea.id === Number(body.contentIdeaId)
        ? {
            ...idea,
            uploadUrl: 'https://open-upload.tiktokapis.com/upload/demo',
            pipelineStatus: 'publish_initialized',
            tiktokUploadStatus: 'init_done',
          }
        : idea)
      lastWorkflowRun = {
        id: ++nextRunId,
        contentIdeaId: Number(body.contentIdeaId),
        workflowType: 'INIT_PUBLISH_TIKTOK',
        status: 'SUCCEEDED',
        attemptNumber: 1,
        errorMessage: null,
        responsePayload: '{}',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
      }
      await route.fulfill({ json: { runId: lastWorkflowRun.id, workflowType: lastWorkflowRun.workflowType, status: 'ACCEPTED' } })
      return
    }

    await route.fulfill({ status: 200, json: {} })
  })

  await page.goto('/tiktok/creation')

  await expect(page.getByText('Compte TikTok cible')).toBeVisible()
  await page.getByRole('button', { name: 'Generer' }).click()
  await expect(page.getByText('Food idea generated by Playwright')).toBeVisible()
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page.getByText('Script genere automatiquement')).toBeVisible()
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page.getByText('Apercu video')).toBeVisible()
  await page.getByRole('button', { name: 'Valider' }).click()
  await page.getByRole('button', { name: 'Preparer upload' }).click()
  await expect(page.getByText('Upload URL')).toBeVisible()
  await expect(page.getByText('https://open-upload.tiktokapis.com/upload/demo')).toBeVisible()
  await expect(page.getByText('Workflow status')).toBeVisible()
})
